[workspace]
# Use the latest resolver available
resolver = "3"
# Include both parts of the library in the workspace
members = [
    "deboa-extras",
    "deboa-fory",
    "deboa-hickory"
]

[workspace.package]
edition = "2021"
authors = ["Rogerio Araújo <rogerio.araujo@gmail.com>"]
repository = "https://github.com/ararog/deboa-contrib"
homepage = "https://github.com/ararog/deboa-contrib"
readme = "README.md"
license = "MIT OR Apache-2.0"
rust-version = "1.85.0"

[workspace.dependencies]
deboa = { path = "../deboa/deboa", default-features = false }
#deboa = { version = "0.1.5-beta.2", default-features = false }
deboa-extras = { path = "deboa-extras" }
deboa-fory = { path = "deboa-fory" }
http = { version = "1.5.0", default-features = false }
http-body-util = { version = "0.1.5", default-features = false }
hyper-body-utils = { path = "../hyper-body-utils" }
#hyper-body-utils = { version = "0.1.17" }

[profile.test]
lto = false

[profile.release]
strip = true
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
