[package]
name = "deboa-extras"
version = "0.1.1-beta.2"
edition.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
description = "deboa extras (serialization, compression, websockets, streams, catchers (middleware) and sse support)."
readme.workspace = true
license.workspace = true
keywords = ["http", "serialization", "compression", "websockets", "sse"]
publish = true
rust-version.workspace = true

[package.metadata.docs.rs]
all-features = true

[features]
default = ["json", "xml", "msgpack", "sse", "utils", "hooks"]
sse = ["dep:hyper-body-utils", "dep:http-body-util", "dep:hyper", "dep:bytes"]
utils = []

# hooks
hooks = ["redirect", "retry"]
redirect = ["dep:deboa", "dep:tackle", "dep:log"]
retry = ["dep:deboa", "dep:tackle", "dep:log"]

# serialization
serialization_all = ["json", "xml", "msgpack", "yaml", "flex", "cbor"]
json = ["simd_json", "dep:serde", "dep:http", "dep:mime", "dep:deboa"]
xml = ["dep:serde-xml-rust", "dep:serde", "dep:http", "dep:mime", "dep:deboa"]
msgpack = ["dep:rmp-serde", "dep:serde", "dep:http", "dep:mime", "dep:deboa"]
yaml = [
  "serde-saphyr/serialize",
  "serde-saphyr/deserialize",
  "dep:serde",
  "dep:http",
  "dep:mime",
  "dep:deboa",
]
flex = ["dep:flexbuffers", "dep:serde", "dep:http", "dep:mime", "dep:deboa"]
cbor = ["ciborium/std", "dep:serde", "dep:http", "dep:deboa"]

# compression
compression_all = ["gzip", "brotli", "deflate"]
brotli = ["dep:brotli", "dep:http", "dep:bytes", "dep:deboa"]
deflate = ["flate2/rust_backend", "dep:http", "dep:bytes", "dep:deboa"]
gzip = ["flate2/rust_backend", "dep:http", "dep:bytes", "dep:deboa"]

simd_json = ["simd-json/serde_impl"]
sonic_json = ["dep:sonic-rs"]

[dependencies]
base64 = { version = "0.23.0", optional = true, default-features = false }
brotli = { version = "9.0.0", optional = true, default-features = false }
bytes = { version = "1.11.1", optional = true, default-features = false }
ciborium = { version = "0.2.2", optional = true, default-features = false }
deboa = { workspace = true, optional = true, default-features = false }
flate2 = { version = "1.1.9", optional = true, default-features = false }
flexbuffers = { version = "25.12.19", optional = true, default-features = false }
futures = { version = "0.3.34", default-features = false, features = ["std"] }
http = { workspace = true, optional = true }
http-body-util = { workspace = true, optional = true }
hyper = { version = "1.11.1", optional = true, default-features = false }
hyper-body-utils = { workspace = true, optional = true, default-features = false }
hyper-util = { version = "0.1.20", optional = true, default-features = false }
log = { version = "0.4.33", optional = true, default-features = false }
mime = { version = "0.3.17", optional = true, default-features = false }
mime_typed = "0.1.7"
pin-project-lite = "0.2.16"
rand = { version = "0.10.1", optional = true, default-features = false }
rmp-serde = { version = "1.3.0", optional = true, default-features = false }
serde = { version = "1.0.217", features = [
  "derive",
], optional = true, default-features = false }
serde-saphyr = { version = "1.0.0", optional = true }
serde-xml-rust = { version = "0.6.0", optional = true, default-features = false }
simd-json = { version = "0.18.0", optional = true, default-features = false }
sonic-rs = { version = "0.5.6", optional = true, default-features = false }
tackle = { version = "0.1.3", optional = true, default-features = false }
thiserror = "2.0.17"
url = "2.5.8"

[dev-dependencies]
caramelo = "0.1.4"
deboa-tokio = { path = "../../deboa-tokio/deboa-tokio", default-features = false, features = [
  "http2",
  #"http1",
  "rust-tls",
  "default-rustls-provider",
  "default-rustls-verifier",
] }
# deboa-tokio = { version = "0.1.4-beta.3", default-features = false, features = [
#   "http2",
#   #"http1",
#   "rust-tls",
#   "default-rustls-provider",
#   "default-rustls-verifier",
# ] }
env_logger = "0.11.11"
tokio = { version = "1.52.3", features = ["macros", "rt-multi-thread"] }
